# Generated by Django 3.2.8 on 2022-01-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='custdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='null', max_length=250, null=True)),
                ('ClientName', models.CharField(default='null', max_length=250, null=True)),
                ('ContactID', models.CharField(default='null', max_length=250, null=True)),
                ('Client_uuid', models.CharField(default='null', max_length=250, null=True)),
                ('Contact_uuid', models.CharField(default='null', max_length=250, null=True)),
                ('PID', models.CharField(default='null', max_length=250, null=True)),
                ('Sample_uuid', models.CharField(default='null', max_length=250, null=True)),
                ('Sample_id', models.CharField(default='null', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='report_reserve_sample_test',
            fields=[
                ('DateSampled', models.CharField(default='null', max_length=250, null=True)),
                ('SampleReceiveDate', models.CharField(default='null', max_length=250, null=True)),
                ('Name', models.CharField(default='null', max_length=250, null=True)),
                ('Type', models.CharField(default='null', max_length=250, null=True)),
                ('Sample_id', models.CharField(default='null', max_length=250, null=True)),
                ('ClientName', models.CharField(default='null', max_length=250, null=True)),
                ('ContactID', models.CharField(default='null', max_length=250, primary_key=True, serialize=False)),
                ('Contact_uuid', models.CharField(default='null', max_length=250, null=True)),
                ('Sample_uuid', models.CharField(default='null', max_length=250, null=True)),
                ('Client_uuid', models.CharField(default='null', max_length=250, null=True)),
                ('Age', models.CharField(default='null', max_length=250, null=True)),
                ('Phone', models.CharField(default='null', max_length=250, null=True)),
                ('Sex', models.CharField(default='null', max_length=250, null=True)),
                ('birthday', models.CharField(default='null', max_length=250, null=True)),
                ('ENName', models.CharField(default='null', max_length=250, null=True)),
                ('remark', models.CharField(default='null', max_length=250, null=True)),
                ('PID', models.CharField(default='null', max_length=250, null=True)),
                ('ClientTo', models.CharField(default='null', max_length=250, null=True)),
            ],
        ),
    ]
